### ISSUE TITLE
Some .form-description positions are wrong

### ISSUE THREAD

**Issue by thedannywahl** [eduridden/moodle-theme_elegance#28]
It doesn't happen to all form settings, but occasionally the positioning of a form description will be incorrect.  Two form elements can have what appears to be the same HTML but one will be positioned correctly and the other incorrectly.

![screen shot 2014-03-01 at 11 56 24 am](https://f.cloud.github.com/assets/743499/2300512/c61da6ea-a0f5-11e3-9507-dbc3df08046a.png)

![screen shot 2014-03-01 at 11 56 49 am](https://f.cloud.github.com/assets/743499/2300513/cce1a30a-a0f5-11e3-830b-d67e0a0bccfd.png)

**Comment by thedannywahl** [comment]
this issue causing this is moodle.css - I'm assuming that it's then the actual less files - but I can't find the reference for the widths or the floats in any .less files.  the fix for this however is:

``` css
.form-item .form-description {
  /* left: 33.3333%; don't declare left positioning */
  float: right; /* current setting is float: left; */
}
```

this will still need an rtl fix
